### ISSUE TITLE
False positive with IIFE using arrow functions

### ISSUE THREAD

**Issue by jwilsson** [MitMaro/eslint-plugin-strict-newline#20]
Hi,
It seems that IIFEs using arrow functions gives false positives:

``` js
(() => {
    'use strict';

    var a;
}());
```

will be reported. 

If this is something you believe should be fixed (given that it's ES6) I'd be happy to submit a PR!

**Comment by MitMaro** [comment]
PR is welcome!

**Comment by jwilsson** [comment]
@MitMaro I got a PR up for review in #22.

**Comment by MitMaro** [comment]
eslint-plugin-strict-newline@1.2.0 has been published. Thanks for the contribution!
